# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.analysis import (
    calculate_linear_time_density as calculate_linear_time_density,
)
from ecoscope.platform.tasks.analysis import create_meshgrid as create_meshgrid
from ecoscope.platform.tasks.analysis import (
    dataframe_column_nunique as dataframe_column_nunique,
)
from ecoscope.platform.tasks.analysis import (
    dataframe_column_sum as dataframe_column_sum,
)
from ecoscope.platform.tasks.analysis import summarize_df as summarize_df
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.io import (
    get_patrol_observations as get_patrol_observations,
)
from ecoscope.platform.tasks.io import persist_df as persist_df
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.transformation import (
    concat_dataframes as concat_dataframes,
)
from ecoscope.platform.tasks.transformation import (
    convert_column_values_to_string as convert_column_values_to_string,
)
from ecoscope.platform.tasks.transformation import (
    decompose_datetime as decompose_datetime,
)
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope.platform.tasks.transformation import with_unit as with_unit
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper_1,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_geojson_layer as create_geojson_layer_1,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map_1
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.spatial_ops import (
    reproject_gdf as reproject_gdf,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    select_columns as select_columns,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    to_quantity as to_quantity,
)
from ecoscope_workflows_ext_mep.tasks.spatial_operations import (
    assert_polygon_types as assert_polygon_types,
)
from ecoscope_workflows_ext_mep.tasks.spatial_operations import (
    get_spatial_features as get_spatial_features_1,
)
from ecoscope_workflows_ext_mep.tasks.spatial_operations import (
    overlay_gdf as overlay_gdf,
)
from ecoscope_workflows_ext_mep.tasks.spatial_operations import (
    set_spatial_features_opacity as set_spatial_features_opacity,
)
from ecoscope_workflows_ext_mep.tasks.transformation import (
    add_bin_colors as add_bin_colors,
)
from ecoscope_workflows_ext_mep.tasks.transformation import (
    add_non_null_flag as add_non_null_flag,
)
from ecoscope_workflows_ext_mep.tasks.transformation import (
    add_time_since_visit as add_time_since_visit,
)
from ecoscope_workflows_ext_mep.tasks.transformation import (
    add_visit_bins as add_visit_bins,
)
from ecoscope_workflows_ext_mep.tasks.transformation import (
    compute_dwell_time as compute_dwell_time,
)
from ecoscope_workflows_ext_mep.tasks.transformation import (
    compute_patrol_effort_fraction as compute_patrol_effort_fraction,
)
from ecoscope_workflows_ext_mep.tasks.transformation import (
    order_bin_categories as order_bin_categories,
)
from ecoscope_workflows_ext_mep.tasks.transformation import (
    reset_dataframe_index as reset_dataframe_index,
)
from ecoscope_workflows_ext_ste.tasks.results import (
    create_spatial_features_layer as create_spatial_features_layer,
)
from ecoscope_workflows_ext_ste.tasks.spatial_operations import (
    combine_deckgl_map_layers as combine_deckgl_map_layers,
)
from ecoscope_workflows_ext_ste.tasks.spatial_operations import (
    compute_view_state_from_gdf as compute_view_state_from_gdf,
)
from ecoscope_workflows_ext_ste.tasks.spatial_operations import (
    envelope_gdf as envelope_gdf,
)
from ecoscope_workflows_ext_ste.tasks.spatial_operations import (
    spatial_join as spatial_join,
)
from ecoscope_workflows_ext_ste.tasks.transformation import (
    add_rgba_from_hex as add_rgba_from_hex,
)
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("time_range") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=[], **(params.get("groupers") or {}))
        .call()
    )

    base_map_defs = (
        task(set_base_maps_pydeck)
        .validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_map_defs") or {}))
        .call()
    )

    select_geo_er = (
        task(get_spatial_features_1)
        .validate()
        .set_task_instance_id("select_geo_er")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            legend_title="Legend",
            **(params.get("select_geo_er") or {}),
        )
        .call()
    )

    get_patrol_obs = (
        task(get_patrol_observations)
        .validate()
        .set_task_instance_id("get_patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            status=["done"],
            include_patrol_details=True,
            raise_on_empty=True,
            sub_page_size=150,
            patrols_overlap_daterange=True,
            **(params.get("get_patrol_obs") or {}),
        )
        .call()
    )

    patrol_obs_trajs = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("patrol_obs_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(relocations=get_patrol_obs, **(params.get("patrol_obs_trajs") or {}))
        .call()
    )

    assert_polygon = (
        task(assert_polygon_types)
        .validate()
        .set_task_instance_id("assert_polygon")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(gdf=select_geo_er, **(params.get("assert_polygon") or {}))
        .call()
    )

    reproject_spatial_3857 = (
        task(reproject_gdf)
        .validate()
        .set_task_instance_id("reproject_spatial_3857")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=select_geo_er,
            target_crs="EPSG:3857",
            **(params.get("reproject_spatial_3857") or {}),
        )
        .call()
    )

    persist_spatial_file = (
        task(persist_df_wrapper_1)
        .validate()
        .set_task_instance_id("persist_spatial_file")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=reproject_spatial_3857,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="er_spatial_file",
            filetypes=["geoparquet"],
            sanitize=True,
            filename_prefix="earthranger",
            **(params.get("persist_spatial_file") or {}),
        )
        .call()
    )

    create_geo_meshgrid = (
        task(create_meshgrid)
        .validate()
        .set_task_instance_id("create_geo_meshgrid")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            aoi=reproject_spatial_3857,
            crs="EPSG:3857",
            intersecting_only=True,
            **(params.get("create_geo_meshgrid") or {}),
        )
        .call()
    )

    overlay_meshgrid_spatial = (
        task(overlay_gdf)
        .validate()
        .set_task_instance_id("overlay_meshgrid_spatial")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left=create_geo_meshgrid,
            right=reproject_spatial_3857,
            how="intersection",
            keep_geom_type=True,
            make_valid=True,
            **(params.get("overlay_meshgrid_spatial") or {}),
        )
        .call()
    )

    meshgrid_idx_id = (
        task(reset_dataframe_index)
        .validate()
        .set_task_instance_id("meshgrid_idx_id")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=overlay_meshgrid_spatial,
            drop=False,
            **(params.get("meshgrid_idx_id") or {}),
        )
        .call()
    )

    reproject_trajs = (
        task(reproject_gdf)
        .validate()
        .set_task_instance_id("reproject_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=patrol_obs_trajs,
            target_crs="EPSG:3857",
            **(params.get("reproject_trajs") or {}),
        )
        .call()
    )

    select_patrol_columns = (
        task(select_columns)
        .validate()
        .set_task_instance_id("select_patrol_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=reproject_trajs,
            columns=["segment_start", "segment_end", "geometry"],
            raise_on_missing=True,
            **(params.get("select_patrol_columns") or {}),
        )
        .call()
    )

    spatial_join_patrol_trajs = (
        task(spatial_join)
        .validate()
        .set_task_instance_id("spatial_join_patrol_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left_df=select_patrol_columns,
            right_df=meshgrid_idx_id,
            how="inner",
            predicate="intersects",
            **(params.get("spatial_join_patrol_trajs") or {}),
        )
        .call()
    )

    summarize_df_grids = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("summarize_df_grids")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=spatial_join_patrol_trajs,
            groupby_cols=["index"],
            reset_index=True,
            summary_params=[
                {
                    "display_name": "last_visited",
                    "aggregator": "max",
                    "column": "segment_end",
                    "original_unit": None,
                    "new_unit": None,
                    "decimal_places": None,
                },
                {
                    "display_name": "first_visited",
                    "aggregator": "min",
                    "column": "segment_start",
                    "original_unit": None,
                    "new_unit": None,
                    "decimal_places": None,
                },
            ],
            **(params.get("summarize_df_grids") or {}),
        )
        .call()
    )

    add_time = (
        task(add_time_since_visit)
        .validate()
        .set_task_instance_id("add_time")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=summarize_df_grids,
            time_range=time_range,
            **(params.get("add_time") or {}),
        )
        .call()
    )

    merge_gridded_stats = (
        task(merge_two_dataframes)
        .validate()
        .set_task_instance_id("merge_gridded_stats")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left=meshgrid_idx_id,
            right=add_time,
            how="left",
            on="index",
            left_on=None,
            right_on=None,
            left_index=False,
            right_index=False,
            fillna_value=None,
            **(params.get("merge_gridded_stats") or {}),
        )
        .call()
    )

    add_null_flag = (
        task(add_non_null_flag)
        .validate()
        .set_task_instance_id("add_null_flag")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=merge_gridded_stats,
            source_column="days_since_visit",
            flag_column="visited",
            **(params.get("add_null_flag") or {}),
        )
        .call()
    )

    add_custom_visit_bins = (
        task(add_visit_bins)
        .validate()
        .set_task_instance_id("add_custom_visit_bins")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_null_flag,
            col="days_since_visit",
            mask_col="visited",
            new_col="visit_bin",
            bins=5,
            scheme="natural_breaks",
            no_data_label="Unvisited",
            use_abs=True,
            **(params.get("add_custom_visit_bins") or {}),
        )
        .call()
    )

    add_visit_bin_colors = (
        task(add_bin_colors)
        .validate()
        .set_task_instance_id("add_visit_bin_colors")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_custom_visit_bins,
            col="visit_bin",
            new_col="hex_color",
            cmap={"type_": "palette", "name": "RdYlGn"},
            no_data_color="#808080",
            no_data_label="Unvisited",
            **(params.get("add_visit_bin_colors") or {}),
        )
        .call()
    )

    reproject_4326 = (
        task(reproject_gdf)
        .validate()
        .set_task_instance_id("reproject_4326")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=add_visit_bin_colors,
            target_crs="EPSG:4326",
            **(params.get("reproject_4326") or {}),
        )
        .call()
    )

    persist_visit = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_visit")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=reproject_4326,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="days_since_patrol_visit",
            filetype="gpkg",
            **(params.get("persist_visit") or {}),
        )
        .call()
    )

    reset_patrol_trajs = (
        task(reset_dataframe_index)
        .validate()
        .set_task_instance_id("reset_patrol_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=reproject_trajs, drop=False, **(params.get("reset_patrol_trajs") or {})
        )
        .call()
    )

    compute_patrol_dwell = (
        task(compute_dwell_time)
        .validate()
        .set_task_instance_id("compute_patrol_dwell")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrol_trajectories=reset_patrol_trajs,
            gridded_spatial_feature=meshgrid_idx_id,
            **(params.get("compute_patrol_dwell") or {}),
        )
        .call()
    )

    merge_dwell_gdf = (
        task(merge_two_dataframes)
        .validate()
        .set_task_instance_id("merge_dwell_gdf")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left=meshgrid_idx_id,
            right=compute_patrol_dwell,
            how="left",
            on="index",
            left_on=None,
            right_on=None,
            left_index=False,
            right_index=False,
            fillna_value=None,
            **(params.get("merge_dwell_gdf") or {}),
        )
        .call()
    )

    reproject_dwell_gdf = (
        task(reproject_gdf)
        .validate()
        .set_task_instance_id("reproject_dwell_gdf")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=merge_dwell_gdf,
            target_crs="EPSG:4326",
            **(params.get("reproject_dwell_gdf") or {}),
        )
        .call()
    )

    add_null_dwell_flag = (
        task(add_non_null_flag)
        .validate()
        .set_task_instance_id("add_null_dwell_flag")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=reproject_dwell_gdf,
            source_column="hours_in_cell",
            flag_column="visited",
            **(params.get("add_null_dwell_flag") or {}),
        )
        .call()
    )

    add_custom_dwell_bins = (
        task(add_visit_bins)
        .validate()
        .set_task_instance_id("add_custom_dwell_bins")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_null_dwell_flag,
            col="hours_in_cell",
            mask_col="visited",
            new_col="visit_bin",
            bins=5,
            scheme="natural_breaks",
            no_data_label="Unvisited",
            use_abs=True,
            **(params.get("add_custom_dwell_bins") or {}),
        )
        .call()
    )

    add_dwell_bin_colors = (
        task(add_bin_colors)
        .validate()
        .set_task_instance_id("add_dwell_bin_colors")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_custom_dwell_bins,
            col="visit_bin",
            new_col="hex_color",
            cmap={"type_": "palette", "name": "RdYlGn"},
            no_data_color="#808080",
            no_data_label="Unvisited",
            **(params.get("add_dwell_bin_colors") or {}),
        )
        .call()
    )

    persist_dwell_geoparquet = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_dwell_geoparquet")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_dwell_bin_colors,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="time_spent_per_cell",
            filetype="gpkg",
            **(params.get("persist_dwell_geoparquet") or {}),
        )
        .call()
    )

    calc_ltd_aoi = (
        task(calculate_linear_time_density)
        .validate()
        .set_task_instance_id("calc_ltd_aoi")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            percentiles=None,
            trajectory_gdf=reproject_trajs,
            meshgrid=overlay_meshgrid_spatial,
            **(params.get("calc_ltd_aoi") or {}),
        )
        .call()
    )

    ltd_unvisited_diff = (
        task(overlay_gdf)
        .validate()
        .set_task_instance_id("ltd_unvisited_diff")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left=overlay_meshgrid_spatial,
            right=calc_ltd_aoi,
            how="difference",
            keep_geom_type=False,
            make_valid=True,
            **(params.get("ltd_unvisited_diff") or {}),
        )
        .call()
    )

    calc_ltd_aoi_full = (
        task(concat_dataframes)
        .validate()
        .set_task_instance_id("calc_ltd_aoi_full")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dfs=[calc_ltd_aoi, ltd_unvisited_diff],
            ensure_columns=["percentile", "density", "area_sqkm"],
            reset_index=True,
            **(params.get("calc_ltd_aoi_full") or {}),
        )
        .call()
    )

    persist_ltd_geoparquet = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_ltd_geoparquet")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=calc_ltd_aoi_full,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="patrols_linear_time_density",
            filetype="gpkg",
            **(params.get("persist_ltd_geoparquet") or {}),
        )
        .call()
    )

    reproject_ltd = (
        task(reproject_gdf)
        .validate()
        .set_task_instance_id("reproject_ltd")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=calc_ltd_aoi_full,
            target_crs="EPSG:4326",
            **(params.get("reproject_ltd") or {}),
        )
        .call()
    )

    add_null_ltd_flag = (
        task(add_non_null_flag)
        .validate()
        .set_task_instance_id("add_null_ltd_flag")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=reproject_ltd,
            source_column="percentile",
            flag_column="visited",
            **(params.get("add_null_ltd_flag") or {}),
        )
        .call()
    )

    add_custom_ltd_bins = (
        task(add_visit_bins)
        .validate()
        .set_task_instance_id("add_custom_ltd_bins")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_null_ltd_flag,
            col="percentile",
            mask_col="visited",
            new_col="visit_bin",
            bins=5,
            scheme="natural_breaks",
            no_data_label="Unvisited",
            use_abs=True,
            **(params.get("add_custom_ltd_bins") or {}),
        )
        .call()
    )

    add_ltd_bin_colors = (
        task(add_bin_colors)
        .validate()
        .set_task_instance_id("add_ltd_bin_colors")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_custom_ltd_bins,
            col="visit_bin",
            new_col="hex_color",
            cmap={"type_": "palette", "name": "RdYlGn"},
            no_data_color="#808080",
            no_data_label="Unvisited",
            **(params.get("add_ltd_bin_colors") or {}),
        )
        .call()
    )

    rename_patrol_cols = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_patrol_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            raise_if_not_found=True,
            df=reproject_trajs,
            duplicate_strategy="suffix",
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "extra__patrol_type__value": "patrol_type",
                "extra__patrol_serial_number": "patrol_serial_number",
                "extra__patrol_status": "patrol_status",
                "extra__patrol_subject": "patrol_subject",
                "extra__subject_id": "subject_id",
                "extra__patrol_id": "patrol_id",
                "extra__patrol_title": "name",
            },
            **(params.get("rename_patrol_cols") or {}),
        )
        .call()
    )

    patrol_segment_date = (
        task(decompose_datetime)
        .validate()
        .set_task_instance_id("patrol_segment_date")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rename_patrol_cols,
            datetime_column="segment_start",
            components=["date"],
            remove_source=False,
            column_prefix=None,
            **(params.get("patrol_segment_date") or {}),
        )
        .call()
    )

    op_summary_table = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("op_summary_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_segment_date,
            groupby_cols=["subject_id", "patrol_subject"],
            reset_index=True,
            summary_params=[
                {
                    "display_name": "distance_km",
                    "aggregator": "sum",
                    "column": "dist_meters",
                    "convert_units": True,
                    "original_unit": "m",
                    "new_unit": "km",
                    "decimal_places": 1,
                },
                {
                    "display_name": "duration_hrs",
                    "aggregator": "sum",
                    "column": "timespan_seconds",
                    "convert_units": True,
                    "original_unit": "s",
                    "new_unit": "h",
                    "decimal_places": 1,
                },
                {
                    "display_name": "patrol_days",
                    "aggregator": "nunique",
                    "column": "segment_start_date",
                    "convert_units": False,
                    "original_unit": None,
                    "new_unit": None,
                    "decimal_places": None,
                },
            ],
            **(params.get("op_summary_table") or {}),
        )
        .call()
    )

    persist_oper_table = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_oper_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=op_summary_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            filetype="csv",
            **(params.get("persist_oper_table") or {}),
        )
        .call()
    )

    persist_patrol_obs = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=get_patrol_obs,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="patrol_observations",
            filetype="gpkg",
            **(params.get("persist_patrol_obs") or {}),
        )
        .call()
    )

    persist_patrol_trajs = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_patrol_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_obs_trajs,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="patrol_trajectories",
            filetype="gpkg",
            **(params.get("persist_patrol_trajs") or {}),
        )
        .call()
    )

    spatial_features_opacity = (
        task(set_spatial_features_opacity)
        .validate()
        .set_task_instance_id("spatial_features_opacity")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=select_geo_er,
            fill_opacity=0.0,
            line_opacity=1.0,
            **(params.get("spatial_features_opacity") or {}),
        )
        .call()
    )

    spatial_features_layer = (
        task(create_spatial_features_layer)
        .validate()
        .set_task_instance_id("spatial_features_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframes=[spatial_features_opacity],
            **(params.get("spatial_features_layer") or {}),
        )
        .call()
    )

    zoom_to_envelope = (
        task(envelope_gdf)
        .validate()
        .set_task_instance_id("zoom_to_envelope")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(gdf=spatial_features_opacity, **(params.get("zoom_to_envelope") or {}))
        .call()
    )

    gdf_image_extent = (
        task(compute_view_state_from_gdf)
        .validate()
        .set_task_instance_id("gdf_image_extent")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            pitch=0,
            bearing=0,
            max_zoom=15,
            gdf=zoom_to_envelope,
            **(params.get("gdf_image_extent") or {}),
        )
        .call()
    )

    decat_time_visit_hex = (
        task(convert_column_values_to_string)
        .validate()
        .set_task_instance_id("decat_time_visit_hex")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=reproject_4326,
            columns=["hex_color"],
            **(params.get("decat_time_visit_hex") or {}),
        )
        .call()
    )

    add_time_visit_rgba = (
        task(add_rgba_from_hex)
        .validate()
        .set_task_instance_id("add_time_visit_rgba")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=decat_time_visit_hex,
            column="hex_color",
            new_column="rgba_color",
            **(params.get("add_time_visit_rgba") or {}),
        )
        .call()
    )

    order_bin_visit_since = (
        task(order_bin_categories)
        .validate()
        .set_task_instance_id("order_bin_visit_since")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_time_visit_rgba,
            bin_column="visit_bin",
            **(params.get("order_bin_visit_since") or {}),
        )
        .call()
    )

    create_time_since_layer = (
        task(create_geojson_layer_1)
        .validate()
        .set_task_instance_id("create_time_since_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            geodataframe=order_bin_visit_since,
            layer_style={
                "filled": True,
                "extruded": False,
                "stroked": True,
                "get_fill_color": "rgba_color",
                "get_line_color": [0, 0, 0],
                "opacity": 0.55,
                "get_line_width": 0.25,
            },
            legend={
                "title": "Time Since Visit (Days)",
                "label_column": "visit_bin",
                "color_column": "rgba_color",
                "sort": "ascending",
                "label_suffix": None,
            },
            **(params.get("create_time_since_layer") or {}),
        )
        .call()
    )

    combine_time_since_layers = (
        task(combine_deckgl_map_layers)
        .validate()
        .set_task_instance_id("combine_time_since_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=spatial_features_layer,
            grouped_layers=create_time_since_layer,
            **(params.get("combine_time_since_layers") or {}),
        )
        .call()
    )

    draw_time_since_map = (
        task(draw_map_1)
        .validate()
        .set_task_instance_id("draw_time_since_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            max_zoom=10,
            static=False,
            title=None,
            geo_layers=combine_time_since_layers,
            tile_layers=base_map_defs,
            legend_style={"placement": "bottom-right"},
            view_state=gdf_image_extent,
            **(params.get("draw_time_since_map") or {}),
        )
        .call()
    )

    time_since_urls = (
        task(persist_text)
        .validate()
        .set_task_instance_id("time_since_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_time_since_map,
            filename="days_since_patrol_visit_map.html",
            **(params.get("time_since_urls") or {}),
        )
        .call()
    )

    decat_dwell_hex = (
        task(convert_column_values_to_string)
        .validate()
        .set_task_instance_id("decat_dwell_hex")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_dwell_bin_colors,
            columns=["hex_color"],
            **(params.get("decat_dwell_hex") or {}),
        )
        .call()
    )

    add_dwell_rgba = (
        task(add_rgba_from_hex)
        .validate()
        .set_task_instance_id("add_dwell_rgba")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=decat_dwell_hex,
            column="hex_color",
            new_column="rgba_color",
            **(params.get("add_dwell_rgba") or {}),
        )
        .call()
    )

    order_bin_dwell_since = (
        task(order_bin_categories)
        .validate()
        .set_task_instance_id("order_bin_dwell_since")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_dwell_rgba,
            bin_column="visit_bin",
            **(params.get("order_bin_dwell_since") or {}),
        )
        .call()
    )

    create_dwell_layer = (
        task(create_geojson_layer_1)
        .validate()
        .set_task_instance_id("create_dwell_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            geodataframe=order_bin_dwell_since,
            layer_style={
                "filled": True,
                "extruded": False,
                "stroked": True,
                "get_fill_color": "rgba_color",
                "get_line_color": [0, 0, 0],
                "opacity": 0.55,
                "get_line_width": 0.25,
            },
            legend={
                "title": "Time Spent(Hours)",
                "label_column": "visit_bin",
                "color_column": "rgba_color",
                "sort": "ascending",
                "label_suffix": None,
            },
            **(params.get("create_dwell_layer") or {}),
        )
        .call()
    )

    combine_dwell_layers = (
        task(combine_deckgl_map_layers)
        .validate()
        .set_task_instance_id("combine_dwell_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=spatial_features_layer,
            grouped_layers=create_dwell_layer,
            **(params.get("combine_dwell_layers") or {}),
        )
        .call()
    )

    draw_dwell_map = (
        task(draw_map_1)
        .validate()
        .set_task_instance_id("draw_dwell_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            max_zoom=10,
            static=False,
            title=None,
            geo_layers=combine_dwell_layers,
            tile_layers=base_map_defs,
            legend_style={"placement": "bottom-right"},
            view_state=gdf_image_extent,
            **(params.get("draw_dwell_map") or {}),
        )
        .call()
    )

    dwell_urls = (
        task(persist_text)
        .validate()
        .set_task_instance_id("dwell_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_dwell_map,
            filename="time_spent_per_grid_map.html",
            **(params.get("dwell_urls") or {}),
        )
        .call()
    )

    decat_ltd_hex = (
        task(convert_column_values_to_string)
        .validate()
        .set_task_instance_id("decat_ltd_hex")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_ltd_bin_colors,
            columns=["hex_color"],
            **(params.get("decat_ltd_hex") or {}),
        )
        .call()
    )

    add_ltd_rgba = (
        task(add_rgba_from_hex)
        .validate()
        .set_task_instance_id("add_ltd_rgba")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=decat_ltd_hex,
            column="hex_color",
            new_column="rgba_color",
            **(params.get("add_ltd_rgba") or {}),
        )
        .call()
    )

    order_bin_ltd_since = (
        task(order_bin_categories)
        .validate()
        .set_task_instance_id("order_bin_ltd_since")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_ltd_rgba,
            bin_column="visit_bin",
            **(params.get("order_bin_ltd_since") or {}),
        )
        .call()
    )

    create_ltd_layer = (
        task(create_geojson_layer_1)
        .validate()
        .set_task_instance_id("create_ltd_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            geodataframe=order_bin_ltd_since,
            layer_style={
                "filled": True,
                "extruded": False,
                "stroked": True,
                "get_fill_color": "rgba_color",
                "get_line_color": [0, 0, 0],
                "opacity": 0.55,
                "get_line_width": 0.25,
            },
            legend={
                "title": "Time Spent",
                "label_column": "visit_bin",
                "color_column": "rgba_color",
                "sort": "ascending",
                "label_suffix": None,
            },
            **(params.get("create_ltd_layer") or {}),
        )
        .call()
    )

    combine_ltd_layers = (
        task(combine_deckgl_map_layers)
        .validate()
        .set_task_instance_id("combine_ltd_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=spatial_features_layer,
            grouped_layers=create_ltd_layer,
            **(params.get("combine_ltd_layers") or {}),
        )
        .call()
    )

    draw_ltd_map = (
        task(draw_map_1)
        .validate()
        .set_task_instance_id("draw_ltd_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            max_zoom=10,
            static=False,
            title=None,
            geo_layers=combine_ltd_layers,
            tile_layers=base_map_defs,
            legend_style={"placement": "bottom-right"},
            view_state=gdf_image_extent,
            **(params.get("draw_ltd_map") or {}),
        )
        .call()
    )

    ltd_urls = (
        task(persist_text)
        .validate()
        .set_task_instance_id("ltd_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_ltd_map,
            filename="ltd_patrols_map.html",
            **(params.get("ltd_urls") or {}),
        )
        .call()
    )

    total_patrols = (
        task(dataframe_column_nunique)
        .validate()
        .set_task_instance_id("total_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="subject_id",
            df=rename_patrol_cols,
            **(params.get("total_patrols") or {}),
        )
        .call()
    )

    total_patrol_dist = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("total_patrol_dist")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="dist_meters",
            df=rename_patrol_cols,
            **(params.get("total_patrol_dist") or {}),
        )
        .call()
    )

    total_patrol_dist_converted = (
        task(with_unit)
        .validate()
        .set_task_instance_id("total_patrol_dist_converted")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            original_unit="m",
            new_unit="km",
            value=total_patrol_dist,
            **(params.get("total_patrol_dist_converted") or {}),
        )
        .call()
    )

    patrol_effort_spatial = (
        task(compute_patrol_effort_fraction)
        .validate()
        .set_task_instance_id("patrol_effort_spatial")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=add_visit_bin_colors, **(params.get("patrol_effort_spatial") or {})
        )
        .call()
    )

    total_patrols_sv_widget = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_patrols_sv_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total Patrols",
            decimal_places=0,
            data=total_patrols,
            **(params.get("total_patrols_sv_widget") or {}),
        )
        .call()
    )

    total_patrol_dist_sv_widget = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_patrol_dist_sv_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total Patrol Distance",
            decimal_places=1,
            data=total_patrol_dist_converted,
            **(params.get("total_patrol_dist_sv_widget") or {}),
        )
        .call()
    )

    patrol_effort_quantity = (
        task(to_quantity)
        .validate()
        .set_task_instance_id("patrol_effort_quantity")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            value=patrol_effort_spatial,
            unit="%",
            **(params.get("patrol_effort_quantity") or {}),
        )
        .call()
    )

    patrol_effort_sv_widget = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("patrol_effort_sv_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Patrol Coverage",
            decimal_places=1,
            data=patrol_effort_quantity,
            **(params.get("patrol_effort_sv_widget") or {}),
        )
        .call()
    )

    time_since_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("time_since_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Days Since Patrol Visit",
            data=time_since_urls,
            **(params.get("time_since_map_widget") or {}),
        )
        .call()
    )

    dwell_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("dwell_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Time Spent Per Grid Cell (Hours)",
            data=dwell_urls,
            **(params.get("dwell_map_widget") or {}),
        )
        .call()
    )

    ltd_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("ltd_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Patrol Linear Time Density",
            data=ltd_urls,
            **(params.get("ltd_map_widget") or {}),
        )
        .call()
    )

    op_summary_table_display = (
        task(map_columns)
        .validate()
        .set_task_instance_id("op_summary_table_display")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            raise_if_not_found=True,
            df=op_summary_table,
            duplicate_strategy="suffix",
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "subject_id": "Subject ID",
                "patrol_subject": "Patrol Subject",
                "distance_km": "Distance (km)",
                "duration_hrs": "Duration (hrs)",
                "patrol_days": "Patrol Days",
            },
            **(params.get("op_summary_table_display") or {}),
        )
        .call()
    )

    op_summary_table_html = (
        task(draw_table)
        .validate()
        .set_task_instance_id("op_summary_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=op_summary_table_display,
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": False,
                "hide_header": False,
            },
            widget_id="Patrol Summary",
            **(params.get("op_summary_table_html") or {}),
        )
        .call()
    )

    op_summary_table_html_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("op_summary_table_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="patrol_summary_table",
            text=op_summary_table_html,
            **(params.get("op_summary_table_html_url") or {}),
        )
        .call()
    )

    op_summary_table_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("op_summary_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Patrol Summary",
            data=op_summary_table_html_url,
            **(params.get("op_summary_table_widget") or {}),
        )
        .call()
    )

    patrol_effort_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("patrol_effort_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                total_patrols_sv_widget,
                total_patrol_dist_sv_widget,
                patrol_effort_sv_widget,
                time_since_map_widget,
                dwell_map_widget,
                ltd_map_widget,
                op_summary_table_widget,
            ],
            time_range=time_range,
            groupers=groupers,
            **(params.get("patrol_effort_dashboard") or {}),
        )
        .call()
    )

    return patrol_effort_dashboard
